In [1]:
import pandas as pd
df = pd.read_excel(r"C:\Users\SIVA\OneDrive\Pictures\Desktop\ETL.xlsx")
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,...,PRODCODE_TRF,NAV_DATE_TRF,NAV_VALUE_TRF,DIV_PERUNIT_TRF,CORPDIVRATE_TRF,SCHEME_TYPE_TRF,RECORD_ID_TRF,UNITS_HELD_TRF,INVESTOR_DENSITY,RANK_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,...,heo1gt,2021-09-09,14.12,1,0.0,Equity,1,MidUnits,2401.250651,Tier02
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,...,p9542,2021-10-06,12.02,1,0.0,FMP,1,MidUnits,1548.414023,Tier02
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,...,b157dz,2021-09-02,1000.02,1,0.0,MoneyMarket,1,MidUnits,2219.637040,Tier01
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,...,hfsfqt,2021-09-06,10.37,1,0.0,FMP,1,MidUnits,60.441594,Tier02
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,...,bscrw,2021-09-09,0.42,1,0.0,Debt,2,MidUnits,2818.731118,Tier02

In [2]:
df.columns

Index(['PRODCODE', 'NAME', 'NAV_DATE', 'NAV_VALUE', 'DIV_PERUNIT',
       'CORPDIVRATE', 'SCHEME_TYPE', 'ISIN_NO', 'RECORD_ID', 'UNITS_HELD',
       'NUM_INVESTORS', 'DAYS_SINCE_INCEPTION', 'RANK', 'PRODCODE_TRF',
       'NAV_DATE_TRF', 'NAV_VALUE_TRF', 'DIV_PERUNIT_TRF', 'CORPDIVRATE_TRF',
       'SCHEME_TYPE_TRF', 'RECORD_ID_TRF', 'UNITS_HELD_TRF',
       'INVESTOR_DENSITY', 'RANK_TRF'],
      dtype='object')

In [9]:
df.shape

(33975, 13)

In [10]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33975 entries, 0 to 33974
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   'PRODCODE'              33975 non-null  object
 1   'NAME'                  33975 non-null  object
 2   'NAV_DATE'              33975 non-null  object
 3   'NAV_VALUE'             33975 non-null  float64
 4   'DIV_PERUNIT'           33975 non-null  float64
 5   'CORPDIVRATE'           33975 non-null  float64
 6   'SCHEME_TYPE'           33975 non-null  object
 7   'ISIN_NO'               33975 non-null  object
 8   'RECORD_ID'             33975 non-null  object
 9   'UNITS_HELD'            33975 non-null  object
 10  'NUM_INVESTORS'         33975 non-null  object
 11  'DAYS_SINCE_INCEPTION'  33975 non-null  object
 12  'RANK'                  33975 non-null  object
dtypes: float64(3), object(10)
memory usage: 3.4+ MB

        'NAV_VALUE'  'DIV_PERUNIT'  'CORPDIVRATE'
count  33975.000000   33975.000000   33975.000000
mean      86.551271       0.003583       0.003583
std      300.980064       0.114562       0.114562
min        0.299730       0.000000       0.000000
25%       12.003596       0.000000       0.000000
50%       13.627145       0.000000       0.000000
75%       36.890000       0.000000       0.000000
max     4564.860859       7.000000       7.000000

In [11]:
df.isnull().sum()

'PRODCODE'                0
'NAME'                    0
'NAV_DATE'                0
'NAV_VALUE'               0
'DIV_PERUNIT'             0
'CORPDIVRATE'             0
'SCHEME_TYPE'             0
'ISIN_NO'                 0
'RECORD_ID'               0
'UNITS_HELD'              0
'NUM_INVESTORS'           0
'DAYS_SINCE_INCEPTION'    0
'RANK'                    0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(4431)

In [13]:
df.dtypes

'PRODCODE'                 object
'NAME'                     object
'NAV_DATE'                 object
'NAV_VALUE'               float64
'DIV_PERUNIT'             float64
'CORPDIVRATE'             float64
'SCHEME_TYPE'              object
'ISIN_NO'                  object
'RECORD_ID'                object
'UNITS_HELD'               object
'NUM_INVESTORS'            object
'DAYS_SINCE_INCEPTION'     object
'RANK'                     object
dtype: object

In [15]:
df.columns=df.columns.str.replace("'","",regex=False).str.strip()

In [16]:
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK
0,'HEO1GT','HDFC Equity Opportunities Fund - II - 1126D M...,'9/9/2021 12:00:00 AM',14.124385,0.0,0.0,'Equity(G)','INF179KC1AF4','15643','1919','4608','1295','41'
1,'P9542','ICICI Prudential Fixed Maturity Plan Series 8...,'10/6/2021 12:00:00 AM',12.019942,0.0,0.0,'FMP(CE)','INF109KC1XL9','25120','2396','3710','2765','36'
2,'B157DZ','Aditya Birla Sun Life Overnight Fund - Daily ...,'9/2/2021 12:00:00 AM',1000.020000,0.0,0.0,'Cash','INF209KB1ZI0','12406','2149','4770','3640','9'
3,'HFSFQT','HDFC FMP 1261D October 2018 (1) - Direct - Qu...,'9/6/2021 12:00:00 AM',10.373400,0.0,0.0,'FMP(CE)','INF179KB19U0','1276','8107','490','2174','33'
4,'BSCRW','Aditya Birla Sun Life Credit Risk Fund Bonus ...,'9/9/2021 12:00:00 AM',0.418332,0.0,0.0,'Bond','INF209KB1P08','29353','1655','4665','1671','24'

In [18]:
df = df.replace(r"['\"]", "", regex=True) 
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,9/9/2021 12:00:00 AM,14.124385,0.0,0.0,Equity(G),INF179KC1AF4,15643,1919,4608,1295,41
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,10/6/2021 12:00:00 AM,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,3710,2765,36
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,9/2/2021 12:00:00 AM,1000.020000,0.0,0.0,Cash,INF209KB1ZI0,12406,2149,4770,3640,9
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,9/6/2021 12:00:00 AM,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,490,2174,33
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,9/9/2021 12:00:00 AM,0.418332,0.0,0.0,Bond,INF209KB1P08,29353,1655,4665,1671,24

In [20]:
df.drop_duplicates(inplace=True)

In [21]:
df.shape

(29544, 13)

In [23]:
df["NAV_DATE"]=pd.to_datetime(df["NAV_DATE"],errors="coerce")

C:\Users\SIVA\AppData\Local\Temp\ipykernel_31152\1997747383.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["NAV_DATE"]=pd.to_datetime(df["NAV_DATE"],errors="coerce")

In [24]:
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,Equity(G),INF179KC1AF4,15643,1919,4608,1295,41
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,3710,2765,36
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,Cash,INF209KB1ZI0,12406,2149,4770,3640,9
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,490,2174,33
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,Bond,INF209KB1P08,29353,1655,4665,1671,24

In [25]:
df["RECORD_ID"]=pd.to_numeric(df["RECORD_ID"],errors="coerce").fillna(0).astype("Int64")
df["RANK"]=pd.to_numeric(df["RANK"],errors="coerce").fillna(0).astype("Int64")
df["UNITS_HELD"]=pd.to_numeric(df["UNITS_HELD"],errors="coerce").fillna(0).astype("Int64")
df["NUM_INVESTORS"]=pd.to_numeric(df["NUM_INVESTORS"],errors="coerce").fillna(0).astype("Int64")
df["DAYS_SINCE_INCEPTION"]=pd.to_numeric(df["DAYS_SINCE_INCEPTION"],errors="coerce").fillna(0).astype("Int64")

In [26]:
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,Equity(G),INF179KC1AF4,15643,1919,4608,1295,41
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,3710,2765,36
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,Cash,INF209KB1ZI0,12406,2149,4770,3640,9
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,490,2174,33
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,Bond,INF209KB1P08,29353,1655,4665,1671,24

In [27]:
df["ISIN_NO"]=df["ISIN_NO"].fillna('0').astype("string")
df["PRODCODE"]=df["PRODCODE"].fillna('0').astype("string")
df["NAME"]=df["NAME"].fillna('0').astype("string")
df["SCHEME_TYPE"]=df["SCHEME_TYPE"].fillna('0').astype("string")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 29544 entries, 0 to 33974
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   PRODCODE              29544 non-null  string
 1   NAME                  29544 non-null  string
 2   NAV_DATE              29544 non-null  datetime64[ns]
 3   NAV_VALUE             29544 non-null  float64
 4   DIV_PERUNIT           29544 non-null  float64
 5   CORPDIVRATE           29544 non-null  float64
 6   SCHEME_TYPE           29544 non-null  string
 7   ISIN_NO               29544 non-null  string
 8   RECORD_ID             29544 non-null  Int64
 9   UNITS_HELD            29544 non-null  Int64
 10  NUM_INVESTORS         29544 non-null  Int64
 11  DAYS_SINCE_INCEPTION  29544 non-null  Int64
 12  RANK                  29544 non-null  Int64
dtypes: Int64(5), datetime64[ns](1), float64(3), string(4)
memory usage: 3.3 MB

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,Equity(G),INF179KC1AF4,15643,1919,4608,1295,41
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,3710,2765,36
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,Cash,INF209KB1ZI0,12406,2149,4770,3640,9
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,490,2174,33
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,Bond,INF209KB1P08,29353,1655,4665,1671,24

In [28]:
df["SCHEME_TYPE"]=df["SCHEME_TYPE"].str.upper()
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,4608,1295,41
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,3710,2765,36
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,4770,3640,9
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,490,2174,33
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,4665,1671,24

In [30]:
#converts into lower
df['PRODCODE_TRF']=df['PRODCODE'].str.lower() .str.strip()
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK,PRODCODE_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,4608,1295,41,heo1gt
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,3710,2765,36,p9542
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,4770,3640,9,b157dz
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,490,2174,33,hfsfqt
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,4665,1671,24,bscrw

In [31]:
df["NAV_DATE_TRF"] = pd.to_datetime(df["NAV_DATE"], format="%Y-%m-%d", errors="coerce")
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK,PRODCODE_TRF,NAV_DATE_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,4608,1295,41,heo1gt,2021-09-09
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,3710,2765,36,p9542,2021-10-06
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,4770,3640,9,b157dz,2021-09-02
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,490,2174,33,hfsfqt,2021-09-06
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,4665,1671,24,bscrw,2021-09-09

In [32]:
# round 2 digits  
df['NAV_VALUE_TRF']=df['NAV_VALUE'].round(2)
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK,PRODCODE_TRF,NAV_DATE_TRF,NAV_VALUE_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,4608,1295,41,heo1gt,2021-09-09,14.12
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,3710,2765,36,p9542,2021-10-06,12.02
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,4770,3640,9,b157dz,2021-09-02,1000.02
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,490,2174,33,hfsfqt,2021-09-06,10.37
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,4665,1671,24,bscrw,2021-09-09,0.42

In [33]:
#convert 
df['DIV_PERUNIT_TRF']=df['DIV_PERUNIT'].apply (lambda x: 1 if x==0 else ( 2 if x==1 else 3))
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK,PRODCODE_TRF,NAV_DATE_TRF,NAV_VALUE_TRF,DIV_PERUNIT_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,4608,1295,41,heo1gt,2021-09-09,14.12,1
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,3710,2765,36,p9542,2021-10-06,12.02,1
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,4770,3640,9,b157dz,2021-09-02,1000.02,1
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,490,2174,33,hfsfqt,2021-09-06,10.37,1
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,4665,1671,24,bscrw,2021-09-09,0.42,1

In [34]:
# convert digit
df['CORPDIVRATE_TRF']=df['CORPDIVRATE'].round(2)
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK,PRODCODE_TRF,NAV_DATE_TRF,NAV_VALUE_TRF,DIV_PERUNIT_TRF,CORPDIVRATE_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,4608,1295,41,heo1gt,2021-09-09,14.12,1,0.0
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,3710,2765,36,p9542,2021-10-06,12.02,1,0.0
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,4770,3640,9,b157dz,2021-09-02,1000.02,1,0.0
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,490,2174,33,hfsfqt,2021-09-06,10.37,1,0.0
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,4665,1671,24,bscrw,2021-09-09,0.42,1,0.0

In [35]:
mapping_rule = {
    "EQUITY(G)": "Equity",
    "EQUITY(S)": "Equity",
    "BOND": "Debt",
    "CASH": "MoneyMarket",
    "ULTRA LIQUID": "MoneyMarket",
    "FMP(CE)": "FMP",
    "INDEX FUND": "Index",
    "ELSS": "TaxSaving",
    "BALANCED": "Hybrid",
    "GILT": "Gilt",
    "GOLD FOF": "FOF",
    "FOF": "FOF",
    "STP": "ShortTermDebt"
}
df["SCHEME_TYPE_TRF"] = df["SCHEME_TYPE"].map(mapping_rule).fillna("Others")
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,NUM_INVESTORS,DAYS_SINCE_INCEPTION,RANK,PRODCODE_TRF,NAV_DATE_TRF,NAV_VALUE_TRF,DIV_PERUNIT_TRF,CORPDIVRATE_TRF,SCHEME_TYPE_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,4608,1295,41,heo1gt,2021-09-09,14.12,1,0.0,Equity
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,3710,2765,36,p9542,2021-10-06,12.02,1,0.0,FMP
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,4770,3640,9,b157dz,2021-09-02,1000.02,1,0.0,MoneyMarket
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,490,2174,33,hfsfqt,2021-09-06,10.37,1,0.0,FMP
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,4665,1671,24,bscrw,2021-09-09,0.42,1,0.0,Debt

In [62]:
import pandas as pd
import numpy as np

# Step 1: Trim spaces (leading/trailing)
df["ISIN_NO"] = df["ISIN_NO"].str.strip()

# Step 2: Convert to uppercase
df["ISIN_NO"] = df["ISIN_NO"].str.upper()

# Step 3: Replace empty strings with NaN
df["ISIN_NO"] = df["ISIN_NO"].replace("", np.nan)
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,...,NAV_DATE_TRF,NAV_VALUE_TRF,DIV_PERUNIT_TRF,CORPDIVRATE_TRF,SCHEME_TYPE_TRF,ISIN_NO_TRF,UNITS_HELD_TRF,INVESTOR_DENSITY,DAYS_SINCE_INCEPTION_TRF,RANK_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,...,2021-09-09,14.12,1,0.0,Equity,INF179KC1AF4,MidUnits,2401.250651,0_5Y,Tier02
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,...,2021-10-06,12.02,1,0.0,FMP,INF109KC1XL9,MidUnits,1548.414023,5_10Y,Tier02
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,...,2021-09-02,1000.02,1,0.0,MoneyMarket,INF209KB1ZI0,MidUnits,2219.63704,5_10Y,Tier01
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,...,2021-09-06,10.37,1,0.0,FMP,INF179KB19U0,MidUnits,60.441594,5_10Y,Tier02
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,...,2021-09-09,0.42,1,0.0,Debt,INF209KB1P08,MidUnits,2818.731118,0_5Y,Tier02

In [68]:
df['RECORD_ID_TRF']=df.groupby("NAV_DATE").cumcount()+1
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,...,NAV_VALUE_TRF,DIV_PERUNIT_TRF,CORPDIVRATE_TRF,SCHEME_TYPE_TRF,ISIN_NO_TRF,UNITS_HELD_TRF,INVESTOR_DENSITY,DAYS_SINCE_INCEPTION_TRF,RANK_TRF,RECORD_ID_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,...,14.12,1,0.0,Equity,INF179KC1AF4,MidUnits,2401.250651,0_5Y,Tier02,1
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,...,12.02,1,0.0,FMP,INF109KC1XL9,MidUnits,1548.414023,5_10Y,Tier02,1
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,...,1000.02,1,0.0,MoneyMarket,INF209KB1ZI0,MidUnits,2219.63704,5_10Y,Tier01,1
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,...,10.37,1,0.0,FMP,INF179KB19U0,MidUnits,60.441594,5_10Y,Tier02,1
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,...,0.42,1,0.0,Debt,INF209KB1P08,MidUnits,2818.731118,0_5Y,Tier02,2

In [45]:
import pandas as pd
import numpy as np


conditions=[
    (df["UNITS_HELD"] == 0),
    (df["UNITS_HELD"] > 0) & (df["UNITS_HELD"] <= 1000),
    (df["UNITS_HELD"] > 1000) & (df["UNITS_HELD"] <= 100000),
    (df["UNITS_HELD"] > 100000)
]

labels = ["ZeroUnits", "LowUnits", "MidUnits", "HighUnits"]
df["UNITS_HELD_TRF"] = np.select(conditions, labels, default="Unknown")
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,...,DAYS_SINCE_INCEPTION,RANK,PRODCODE_TRF,NAV_DATE_TRF,NAV_VALUE_TRF,DIV_PERUNIT_TRF,CORPDIVRATE_TRF,SCHEME_TYPE_TRF,ISIN_NO_TRF,UNITS_HELD_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,...,1295,41,heo1gt,2021-09-09,14.12,1,0.0,Equity,INF179KC1AF4,MidUnits
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,...,2765,36,p9542,2021-10-06,12.02,1,0.0,FMP,INF109KC1XL9,MidUnits
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,...,3640,9,b157dz,2021-09-02,1000.02,1,0.0,MoneyMarket,INF209KB1ZI0,MidUnits
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,...,2174,33,hfsfqt,2021-09-06,10.37,1,0.0,FMP,INF179KB19U0,MidUnits
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,...,1671,24,bscrw,2021-09-09,0.42,1,0.0,Debt,INF209KB1P08,MidUnits

In [47]:
df.tail()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,...,DAYS_SINCE_INCEPTION,RANK,PRODCODE_TRF,NAV_DATE_TRF,NAV_VALUE_TRF,DIV_PERUNIT_TRF,CORPDIVRATE_TRF,SCHEME_TYPE_TRF,ISIN_NO_TRF,UNITS_HELD_TRF
33970,HGFGPG,HDFC Large and Mid Cap Fund - Regular Plan - G...,2021-09-17,179.459989,0.0,0.0,EQUITY(G),INF179KA1RT1,16851,7739,...,653,26,hgfgpg,2021-09-17,179.46,1,0.0,Equity,INF179KA1RT1,MidUnits
33971,P1779P,ICICI Prudential Floating Interest Fund - Othe...,2021-09-01,153.989100,0.0,0.0,ULTRA LIQUID,INF109K01WQ9,6266,8861,...,1199,96,p1779p,2021-09-01,153.99,1,0.0,MoneyMarket,INF109K01WQ9,MidUnits
33972,B1377X,Aditya Birla Sun Life Fixed Term Plan - Series...,2021-09-02,13.261800,0.0,0.0,FMP(CE),INF209KB1QE8,11285,4310,...,1862,62,b1377x,2021-09-02,13.26,1,0.0,FMP,INF209KB1QE8,MidUnits
33973,HEO1DT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-03,14.120000,0.0,0.0,EQUITY(G),INF179KC1AG2,861,217,...,1202,75,heo1dt,2021-09-03,14.12,1,0.0,Equity,INF179KC1AG2,LowUnits
33974,HFRXQR,HDFC FMP 1122D August 2018 (1) - Regular - Qua...,2021-09-12,9.964665,0.0,0.0,FMP(CE),INF179KB16M3,15796,1311,...,1846,88,hfrxqr,2021-09-12,9.96,1,0.0,FMP,INF179KB16M3,MidUnits

In [49]:
df["INVESTOR_DENSITY"] = df["NUM_INVESTORS"] / (df["UNITS_HELD"] / 1000)
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,...,RANK,PRODCODE_TRF,NAV_DATE_TRF,NAV_VALUE_TRF,DIV_PERUNIT_TRF,CORPDIVRATE_TRF,SCHEME_TYPE_TRF,ISIN_NO_TRF,UNITS_HELD_TRF,INVESTOR_DENSITY
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,...,41,heo1gt,2021-09-09,14.12,1,0.0,Equity,INF179KC1AF4,MidUnits,2401.250651
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,...,36,p9542,2021-10-06,12.02,1,0.0,FMP,INF109KC1XL9,MidUnits,1548.414023
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,...,9,b157dz,2021-09-02,1000.02,1,0.0,MoneyMarket,INF209KB1ZI0,MidUnits,2219.63704
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,...,33,hfsfqt,2021-09-06,10.37,1,0.0,FMP,INF179KB19U0,MidUnits,60.441594
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,...,24,bscrw,2021-09-09,0.42,1,0.0,Debt,INF209KB1P08,MidUnits,2818.731118

In [52]:
df['DAYS_SINCE_INCEPTION_TRF']=df["DAYS_SINCE_INCEPTION"].apply(
    lambda x: "New" if x <= 365 
              else "0_5Y" if x <= 1825 
              else "5_10Y" if x <= 3650 
              else "10Y_PLUS")
df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,...,PRODCODE_TRF,NAV_DATE_TRF,NAV_VALUE_TRF,DIV_PERUNIT_TRF,CORPDIVRATE_TRF,SCHEME_TYPE_TRF,ISIN_NO_TRF,UNITS_HELD_TRF,INVESTOR_DENSITY,DAYS_SINCE_INCEPTION_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,...,heo1gt,2021-09-09,14.12,1,0.0,Equity,INF179KC1AF4,MidUnits,2401.250651,0_5Y
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,...,p9542,2021-10-06,12.02,1,0.0,FMP,INF109KC1XL9,MidUnits,1548.414023,5_10Y
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,...,b157dz,2021-09-02,1000.02,1,0.0,MoneyMarket,INF209KB1ZI0,MidUnits,2219.63704,5_10Y
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,...,hfsfqt,2021-09-06,10.37,1,0.0,FMP,INF179KB19U0,MidUnits,60.441594,5_10Y
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,...,bscrw,2021-09-09,0.42,1,0.0,Debt,INF209KB1P08,MidUnits,2818.731118,0_5Y

In [25]:
df["RANK_TRF"] = df["RANK"].apply(
    lambda x: "Tier01" if 1 <= x <= 20
              else "Tier02" if 21 <= x <= 50
              else "Tier03" if 51 <= x <= 100
              else "Tier04" if 101 <= x <= 200
              else "Tier05")

df.head()

,PRODCODE,NAME,NAV_DATE,NAV_VALUE,DIV_PERUNIT,CORPDIVRATE,SCHEME_TYPE,ISIN_NO,RECORD_ID,UNITS_HELD,...,PRODCODE_TRF,NAV_DATE_TRF,NAV_VALUE_TRF,DIV_PERUNIT_TRF,CORPDIVRATE_TRF,SCHEME_TYPE_TRF,RECORD_ID_TRF,UNITS_HELD_TRF,INVESTOR_DENSITY,RANK_TRF
0,HEO1GT,HDFC Equity Opportunities Fund - II - 1126D Ma...,2021-09-09,14.124385,0.0,0.0,EQUITY(G),INF179KC1AF4,15643,1919,...,heo1gt,2021-09-09,14.12,1,0.0,Equity,1,MidUnits,2401.250651,Tier02
1,P9542,ICICI Prudential Fixed Maturity Plan Series 85...,2021-10-06,12.019942,0.0,0.0,FMP(CE),INF109KC1XL9,25120,2396,...,p9542,2021-10-06,12.02,1,0.0,FMP,1,MidUnits,1548.414023,Tier02
2,B157DZ,Aditya Birla Sun Life Overnight Fund - Daily I...,2021-09-02,1000.020000,0.0,0.0,CASH,INF209KB1ZI0,12406,2149,...,b157dz,2021-09-02,1000.02,1,0.0,MoneyMarket,1,MidUnits,2219.637040,Tier01
3,HFSFQT,HDFC FMP 1261D October 2018 (1) - Direct - Qua...,2021-09-06,10.373400,0.0,0.0,FMP(CE),INF179KB19U0,1276,8107,...,hfsfqt,2021-09-06,10.37,1,0.0,FMP,1,MidUnits,60.441594,Tier02
4,BSCRW,Aditya Birla Sun Life Credit Risk Fund Bonus D...,2021-09-09,0.418332,0.0,0.0,BOND,INF209KB1P08,29353,1655,...,bscrw,2021-09-09,0.42,1,0.0,Debt,2,MidUnits,2818.731118,Tier02

In [ ]:
df.to_excel("CLEANED_DATA.xLSX",index=False)